# 함수(날짜 관련)

```sql
-- 함수(날짜)

/*
    SYSDATE
    SYSTIMESTAMP -> 일반적
    CURRENT_TIMESTAMP
    CURRENT_DATE
*/

SELECT CURRENT_DATE
FROM DUAL;

-- EXTRACT : 추출
-- YEAR, MONTH, DAY, HOUR, MINUTE, SECOND
SELECT EXTRACT(YEAR FROM SYSTIMESTAMP) AS 년도,
       EXTRACT(MONTH FROM SYSTIMESTAMP) AS 월
FROM DUAL;

-- NEXT_DAY : 가장 가까운 다음 날짜(요일 지정)
SELECT NEXT_DAY(SYSDATE, '금')
FROM DUAL;


-- TO_DATE : 날짜로 변환
SELECT TO_DATE('2022/05/19')
FROM DUAL;

-- BETWEEN
SELECT MONTHS_BETWEEN(SYSDATE,TO_DATE('2021/05/19'))
FROM DUAL;

-- ROUND
SELECT ROUND(SYSDATE, 'YEAR')
FROM DUAL;

-- TRUNC
SELECT TRUNC(TO_DATE('2022/12/10'), 'YEAR')
FROM DUAL;
```